name = "fe-news-worker"
compatibility_date = "2025-04-03"
main = "./src/worker/index.js"

[assets]
directory = "./dist/client"
binding = "ASSETS"
run_worker_first = true

[vars]
PRODUCTION_BASE_URL = "https://forhyundaisofteer.github.io/fe-news"